# SPDX-License-Identifier: GPL-2.0

obj-y := core.o
obj-y += sysfs.o
obj-$(CONFIG_CONGESTIER_PGTEMP_PEBS) += pgtemp.o
obj-$(CONFIG_CONGESTIER_TRANSACTIONAL_MIGRATE) += migrate.o
obj-$(CONFIG_CONGESTIER_SHADOW_PAGING) += migrate.o
